### PR TITLE
#167312475 Add Linting to the Travis CI

### PR DESCRIPTION
**Pull request by HabibSentongo**
#### What does this PR do?
- Configure EsLint on Travis CI

#### Description of Task to be completed?
- add eslint scripts to package.json
- add eslint script to .travis.yml
- add eslint configuration to .eslintrc.json

#### How should this be manually tested?

- Lookout for ESLint messages on later raised PRs and also check out the set configurations in the changed files.

#### What are the relevant pivotal tracker stories?

- Story ID - [167312475](https://www.pivotaltracker.com/story/show/167312475)

### CODE REVIEW

**Review by neelxie — APPROVED** [review]
@HabibSentongo I leap of faith for this one since it can only be tested after being set up on the develop.

**Review by Emmanuelaaron — APPROVED** [review]
It looks good to me and I think we are good to go

**Review by jennizalwango — APPROVED** [review]
okay thanks for the implementations

**Review by alexxsanya — APPROVED** [review]
Great work @HabibSentongo

**Pull request merged**
