### PR TITLE
#166187811 Setup Travis CI

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Update TravisCI to run tests.

#### Description of Task to be completed?

Configure Travis for this project
Get project badge and add it to readme

#### How should this be manually tested?

- Git fetch this repo locally in the terminal with `git fetch origin ch-setup-travisci-166187811
- Then click on the badge that is appearing on the ReadMe
- This [here ](https://travis-ci.org/andela/ah-frontend-realers/builds/553770229)should take you to Travis to show that the build is passing

#### Any background context you want to provide?

I have set up Continuous Integration for this project with Travis to run our builds.

#### What are the relevant pivotal tracker stories?

#[166187811](https://www.pivotaltracker.com/story/show/166187811)

#### Screenshots

Screenshot 2019-07-03 at 17 23 18

### CODE REVIEW

**Review by alexxsanya — CHANGES_REQUESTED** [review]
@neelxie I notice this PR happen to have 2 commits. I suggest you squash them. 

Screenshot 2019-07-05 at 09 29 32

**Comment by neelxie** [comment]
> @neelxie I notice this PR happen to have 2 commits. I suggest you squash them.
> 
> Screenshot 2019-07-05 at 09 29 32

I think you need to refresh your page or something is wrong on your side because everything seems set on my end and here is how everything looks like on my end.

Screenshot 2019-07-05 at 10 07 37

Screenshot 2019-07-05 at 10 07 46

Screenshot 2019-07-05 at 10 08 00

If am not mistaken your screenshot was taken before the call for you guys to review, if possible could you please refresh and I will await your feedback.

**Review by Emmanuelaaron — APPROVED** [review]
After clicking on the travisc link, It looks good to me and I think we are good to go. Thanks

**Comment by alexxsanya** [comment]
> > @neelxie I notice this PR happen to have 2 commits. I suggest you squash them.
> > Screenshot 2019-07-05 at 09 29 32
> 
> I think you need to refresh your page or something is wrong on your side because everything seems set on my end and here is how everything looks like on my end.
> 
> Screenshot 2019-07-05 at 10 07 37
> 
> Screenshot 2019-07-05 at 10 07 46
> 
> Screenshot 2019-07-05 at 10 08 00
> 
> If am not mistaken your screenshot was taken before the call for you guys to review, if possible could you please refresh and I will await your feedback.

I have refreshed and it's good. I actually received an email requesting to review and I found so. anyway, it's good that it's good now.

**Review by HabibSentongo — APPROVED** [review]
I have followed the link and confirmed the build is successful and the test coverage is 100%

**Review by alexxsanya — APPROVED** [review]
I must say this good for us to progress. well done @neelxie

**Review by jennizalwango — COMMENTED** [review]
well, @neelxie, l have tested out your branch and everything works fine so on my side l think your good to go.

**Review by jennizalwango — APPROVED** [review]
well, @neelxie, l have tested out your branch and everything works fine so on my side l think your good to go.

**Pull request merged**
