### PR TITLE
167127214 Setup and deploy the app to Heroku

### PR DESCRIPTION
**Pull request by alexxsanya**
#### What does this PR do?
- Setup and deploy base application to Heroku

#### Description of Task to be completed?
- create account on heroku
- deploy the apps on heroku

#### How should this be manually tested?
- Below is a screenshot of the review and staging app 
Screenshot 2019-07-08 at 17 57 56

- Click on this [link](https://authors-frontend-staging.herokuapp.com/) to confirm that the staging link is working.

#### Any background context you want to provide?
The project currently had no heroku setup for continuous delivery and with no review apps for the raise PR. so with this PR, the integration will be set for our project.

#### What are the relevant pivotal tracker stories?

- Story ID - [167127214](https://www.pivotaltracker.com/story/show/167127214)

**DEV_NOTE**
- Kindly note that I have kept the **server.js** file  in ES5 format because currently node.js currently doesn't fully understand some of ES6 syntax like **import**

### CODE REVIEW

**Review by neelxie — CHANGES_REQUESTED** [review]
Screenshot 2019-07-08 at 18 09 44

Good velocity @alexxsanya but could you kindly action on this below.

Screenshot 2019-07-08 at 18 07 09

**Review by HabibSentongo — APPROVED** [review]
The deployment is successful when I rerun it and I see you have all the necessary Heroku settings. This is good to go.

**Comment by alexxsanya** [comment]
> Screenshot 2019-07-08 at 18 09 44
> 
> Good velocity @alexxsanya but could you kindly action on this below.
> 
> Screenshot 2019-07-08 at 18 07 09

@neelxie kindly read through the PR notice, please.

**Review by neelxie — APPROVED** [review]
Okay thank you, for the deployment @alexxsanya keep up the good work.

**Review by jennizalwango — COMMENTED** [review]
well, l have followed the description on your PR and everything is working well, 
l think you good to go.

**Review by jennizalwango — APPROVED** [review]

**Review by Emmanuelaaron — APPROVED** [review]
I can comfortably confirm that we are good to go

**Pull request merged**
