### PR TITLE
#166187814 Run Code Climate Test Coverage

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Set up testing environment for project

#### Description of Task to be completed?

- Add repo to code climate
- Add badges to Readme file
- Configure Travis to send requests to code climate

#### How should this be manually tested?

* -   This is an online build that gets triggered by the `.travis.yml` file in our repo and since develop is set as the default branch the badge will only show on that branch.

#### Any background context you want to provide?

This application must have all tests passing for the build to pass

#### What are the relevant pivotal tracker stories?

#[166187814](https://www.pivotaltracker.com/story/show/166187814)

### CODE REVIEW

**Review by jennizalwango — COMMENTED** [review]
hey @neelxie, Yes Good work l have tested and saw the build pass although on the part of `how this can be manually tested is not clear enough `

**Review by alexxsanya — APPROVED** [review]
@neelxie nice work here but in the readme, I am suggesting you align the badges on the same line instead of each being on a separate line.

**Comment by neelxie** [comment]
> @neelxie nice work here but in the readme, I am suggesting you align the badges on the same line instead of each being on a separate line.

Since there is not much in the Readme file, for now they can have separate lines.

**Comment by neelxie** [comment]
> hey @neelxie, Yes Good work l have tested and saw the build pass although on the part of `how this can be manually tested is not clear enough `

Thank you @jennizalwango let me re-paste this for you here again *This is an online build that gets triggered by the `.travis.yml` file in our repo and since develop is set as the default branch the badge will only show on that branch.*

That clearly states that the only perfect way this task can be tested is if it is in the Develop branch of our repo, considering the badge is set for the Develop branch as the default.

**Review by jennizalwango — APPROVED** [review]

**Review by Emmanuelaaron — APPROVED** [review]
Great work @neelxie

**Review by HabibSentongo — APPROVED** [review]
I see everything is in the right place.

**Comment by AGMETEOR** [comment]
@neelxie check the test coverage badge, it's showing a question mark instead.

**Comment by neelxie** [comment]
> @neelxie check the test coverage badge, it's showing a question mark instead.

The code climate badges were configured to work only on the Develop branch, that is why it is not working yet because the branch that has the badge has not been merged to the develop but for demonstration purposes let me change the configured default branch to my task branch to show it working

Screenshot 2019-07-09 at 09 59 06

above I change the default branch from develop to my task branch

Screenshot 2019-07-09 at 09 58 24

as you can see, it shows automatically

Screenshot 2019-07-09 at 09 59 34

Here we see the repo having the badges on the configured branch, this is what will happen with the develop branch.

**Pull request merged**
