### PR TITLE
#167116225 setup hound

### PR DESCRIPTION
**Pull request by jennizalwango**
#### What does this PR do?
- set up hound for our project.
####  Description of the task completed?
- Hound reviews code in your GitHub pull requests. 
- If Hound finds any issues it will comment inline on your pull request.
### How can this be manually tested?
Just create a pull request then hound will be seen doing its job
the rest of the work will be got when file is merged but as for now that is it
#### what are the relevant pivotal tracker stories?
[#167116225](url)

### CODE REVIEW

**Review by alexxsanya — COMMENTED** [review]
@jennizalwango I can't happen to see how to manually test this PR. kindly share on how we can review this PR.

**Comment by jennizalwango** [comment]
> @jennizalwango I can't happen to see how to manually test this PR. kindly share on how we can review this PR.

@alexxsanya l am done with the feedback on my PR

**Review by neelxie — COMMENTED** [review]
@jennizalwango Could you kindly throw more light on this, do you mean it can only be tested by creating a Pull Request?
Screenshot 2019-07-08 at 10 25 10

**Comment by jennizalwango** [comment]
> @jennizalwango Could you kindly throw more light on this, do you mean it can only be tested by creating a Pull Request?
> Screenshot 2019-07-08 at 10 25 10

Yes

**Comment by HabibSentongo** [comment]
> > @jennizalwango Could you kindly throw more light on this, do you mean it can only be tested by creating a Pull Request?
> > Screenshot 2019-07-08 at 10 25 10
> 
> Yes

Let me wait to review so I can first fully understand this in the skills session you are going to take us through.

**Review by alexxsanya — APPROVED** [review]
@jennizalwango Nice work. I believe we are good to go.

**Review by Emmanuelaaron — APPROVED** [review]
I can comfortably confirm that we are good to go having seen it run on @neelxie's PR.
Great work @jennizalwango

**Review by neelxie — APPROVED** [review]
Great work @jennizalwango

**Review by HabibSentongo — APPROVED** [review]
This works perfectly well as we have already observed on Derrick's PR.

**Pull request merged**
