### PR TITLE
Chore(Test Environment): Set up test environment

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Set up testing environment for project

#### Description of Task to be completed?

Install jest and enzyme
Create setupTest.js file
Set up testing environment

#### How should this be manually tested?

* -	Git fetch this repo locally in the terminal with `git fetch origin ch-setup-test-environment-166187810
* -	Install application dependencies: `npm install`
* -	Run application tests: `npm test`
* -	Check test coverage: `npx jest -–coverage`

#### Any background context you want to provide?

This application did not have a testing environment nor tests, I have set up both.

#### What are the relevant pivotal tracker stories?

#[166187810](https://www.pivotaltracker.com/story/show/166187810)

#### Screenshots

Passing Tests with the coverage

Screenshot 2019-07-02 at 18 11 19

### CODE REVIEW

**Review by alexxsanya — COMMENTED** [review]
@neelxie  I can't happen to get everything passing and even the coverage is not showing, following your procedures as you may see below.  what could I be missing ?.

Screenshot 2019-07-02 at 19 24 00

**Review by Emmanuelaaron — APPROVED** [review]
Screenshot 2019-07-03 at 09 48 31
Screenshot 2019-07-03 at 09 54 19


Having tested the PR following your suggested procedure, I think we are good to go only that you have to update the `App.test.js` to `App.test.jsx` to eliminate complaints from eslint
Screenshot 2019-07-03 at 09 54 58

Great Job @neelxie.

**Comment by alexxsanya** [comment]
> Screenshot 2019-07-03 at 09 48 31
> 
> Having tested the PR following your suggested procedure, I think we are good to go. Great Job @neelxie

@Emmanuelaaron how can this be good when you are not having the coverage as @neelxie got them.

**Comment by neelxie** [comment]
> @neelxie I can't happen to get everything passing and even the coverage is not showing, following your procedures as you may see below. what could I be missing ?.
> 
> Screenshot 2019-07-02 at 19 24 00

@alexxsanya do relax the error is on your end instead of typing `npx jest --coverage` you have `npx jest -coverage` check that out, fix it and please do get back to me with the results, I await your kind feedback.

**Comment by neelxie** [comment]
> > Screenshot 2019-07-03 at 09 48 31
> > Having tested the PR following your suggested procedure, I think we are good to go. Great Job @neelxie
> 
> @Emmanuelaaron how can this be good when you are not having the coverage as @neelxie got them.

@alexxsanya Please refer to the above comment for this, thank you.

**Comment by alexxsanya** [comment]
> > > Screenshot 2019-07-03 at 09 48 31
> > > Having tested the PR following your suggested procedure, I think we are good to go. Great Job @neelxie
> > 
> > 
> > @Emmanuelaaron how can this be good when you are not having the coverage as @neelxie got them.
> 
> @alexxsanya Please refer to the above comment for this, thank you.

@neelxie thanks thanks. now getting it right.
Screenshot 2019-07-03 at 09 57 06

**Comment by Emmanuelaaron** [comment]
> > Screenshot 2019-07-03 at 09 48 31
> > Having tested the PR following your suggested procedure, I think we are good to go. Great Job @neelxie
> 
> @Emmanuelaaron how can this be good when you are not having the coverage as @neelxie got them.

I had initially used a wrong command  `npx jest -coverage` other than `npx jest -–coverage`

**Review by alexxsanya — APPROVED** [review]
@neelxie after pointing me in the right direction, I believe we are good to go. well done.

**Review by Emmanuelaaron — CHANGES_REQUESTED** [review]
Screenshot 2019-07-03 at 09 54 58
Please consider updating the `App.test.js` file to `App.test.jsx` to prevent complaints from eslint

**Review by jennizalwango — COMMENTED** [review]
good work @neelxie  l am just requesting for an explanation why do we  run 
`npx jest -–coverage` what does it do.
Then l understand both jest and enzyme are used to test react applications but why do we have both jest and enzyme, l am just requesting for a clear explanation why we have both of them in our package.json file.
Then also as you work @Emmanuelaaron because l have the same issues with me
Then also another thing 
Screenshot 2019-07-03 at 10 18 39 AM

Can you please work on this as well because its an eslint issue.
Screenshot 2019-07-03 at 10 23 11 AM
Its like `enzyme-adapter-react-16` should be listed in the project's dependencies, not devDependencies. 
And the thing is if l try to change any of those these file l will have to commit and push which shouldn't be the case. Please look into this or correct me if l am wrong.
Thanks

**Comment by neelxie** [comment]
> Screenshot 2019-07-03 at 09 54 58
> 
> Please consider updating the `App.test.js` file to `App.test.jsx` to prevent complaints from eslint

@Emmanuelaaron Thank you, I have worked on you feedback and re-pushed please here is a screenshot to show the changes

> Screenshot 2019-07-03 at 09 54 58
> 
> Please consider updating the `App.test.js` file to `App.test.jsx` to prevent complaints from eslint

Thank you @Emmanuelaaron I have worked on your feedback and here is a screenshot of the changes 

Screenshot 2019-07-03 at 10 11 48

**Review by jennizalwango — COMMENTED** [review]
good work @neelxie  l am just resting for an explanation why do we  run 
`npx jest -–coverage` what does it do.
Then l understand both jest and enzyme are used to test react applications but why do we have both jest and enzyme, l am just requesting for a clear explanation why we have both of them in our package.json file.
Then also as you work @Emmanuelaaron because l have the same issues with me
Then also another thing 
Screenshot 2019-07-03 at 10 18 39 AM

Can you please work on this as well because its an eslint issue.
Screenshot 2019-07-03 at 10 23 11 AM
Its like `enzyme-adapter-react-16` should be listed in the project's dependencies, not devDependencies. 
Please look into this or correct me if l am wrong
Thanks

@jennizalwango Thank you, for your inquiry, truth is I had missed a few linting errors, I have reviewed them and fixed all of them thank you again.

**Review by HabibSentongo — APPROVED** [review]
Screenshot 2019-07-03 at 10 31 10

I have followed your directions to test and confirmed that everything is working fine as you can see above in the screenshot.
Other than the basic missing linting that @jennizalwango has pointed out, I think everything is okay.

**Review by Emmanuelaaron — APPROVED** [review]
having worked on all the feedback, I think we are good to go.

**Comment by jennizalwango** [comment]
> good work @neelxie l am just resting for an explanation why do we run
> `npx jest -–coverage` what does it do.
> Then l understand both jest and enzyme are used to test react applications but why do we have both jest and enzyme, l am just requesting for a clear explanation why we have both of them in our package.json file.
> Then also as you work @Emmanuelaaron because l have the same issues with me
> Then also another thing
> Screenshot 2019-07-03 at 10 18 39 AM
> 
> Can you please work on this as well because its an eslint issue.
> Screenshot 2019-07-03 at 10 23 11 AM
> Its like `enzyme-adapter-react-16` should be listed in the project's dependencies, not devDependencies.
> Please look into this or correct me if l am wrong
> Thanks
> 
> @jennizalwango Thank you, for your inquiry, truth is I had missed a few linting errors, I have reviewed them and fixed all of them thank you again.
Good work @neelxie , 
But there is still some feedback up that you have not touched please consider this as well

**Comment by neelxie** [comment]
> > good work @neelxie l am just resting for an explanation why do we run
> > `npx jest -–coverage` what does it do.
> > Then l understand both jest and enzyme are used to test react applications but why do we have both jest and enzyme, l am just requesting for a clear explanation why we have both of them in our package.json file.
> > Then also as you work @Emmanuelaaron because l have the same issues with me
> > Then also another thing
> > Screenshot 2019-07-03 at 10 18 39 AM
> > Can you please work on this as well because its an eslint issue.
> > Screenshot 2019-07-03 at 10 23 11 AM
> > Its like `enzyme-adapter-react-16` should be listed in the project's dependencies, not devDependencies.
> > Please look into this or correct me if l am wrong
> > Thanks
> > @jennizalwango Thank you, for your inquiry, truth is I had missed a few linting errors, I have reviewed them and fixed all of them thank you again.
> > Good work @neelxie ,
> > But there is still some feedback up that you have not touched please consider this as well

@jennizalwango `npx jest --coverage` when you do check our scripts in the package.json file we run our tests bu running the test scripts, which runs `jest` the test runner, the `--coverage` is added to the `jest` the script which creates a directory that contains the coverage report, `npx` I use it in assumption that you have your dependencies installed to that particular directory and not globally, because if they are globally installed `jest --coverage` does work best as well. Thank you.

Jest is a unit testing framework. It is a test runner, assertion and mocking library. Enzyme is a javascript utility for testing react. It adds additional utility methods and functionality, It can not be used without a test runner like jest yet jest can be used alone as well, but for the additional functionality provided by enzyme using them together makes testing easier and gives us broader choices from snapshot testing, assertions and mocking. [Here is a resource](https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675) you could indulge yourself for more insight.

**Comment by jennizalwango** [comment]
> > > good work @neelxie l am just resting for an explanation why do we run
> > > `npx jest -–coverage` what does it do.
> > > Then l understand both jest and enzyme are used to test react applications but why do we have both jest and enzyme, l am just requesting for a clear explanation why we have both of them in our package.json file.
> > > Then also as you work @Emmanuelaaron because l have the same issues with me
> > > Then also another thing
> > > Screenshot 2019-07-03 at 10 18 39 AM
> > > Can you please work on this as well because its an eslint issue.
> > > Screenshot 2019-07-03 at 10 23 11 AM
> > > Its like `enzyme-adapter-react-16` should be listed in the project's dependencies, not devDependencies.
> > > Please look into this or correct me if l am wrong
> > > Thanks
> > > @jennizalwango Thank you, for your inquiry, truth is I had missed a few linting errors, I have reviewed them and fixed all of them thank you again.
> > > Good work @neelxie ,
> > > But there is still some feedback up that you have not touched please consider this as well
> 
> @jennizalwango `npx jest --coverage` when you do check our scripts in the package.json file we run our tests bu running the test scripts, which runs `jest` the test runner, the `--coverage` is added to the `jest` the script which creates a directory that contains the coverage report, `npx` I use it in assumption that you have your dependencies installed to that particular directory and not globally, because if they are globally installed `jest --coverage` does work best as well. Thank you.
> 
> Jest is a unit testing framework. It is a test runner, assertion and mocking library. Enzyme is a javascript utility for testing react. It adds additional utility methods and functionality, It can not be used without a test runner like jest yet jest can be used alone as well, but for the additional functionality provided by enzyme using them together makes testing easier and gives us broader choices from snapshot testing, assertions and mocking. [Here is a resource](https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675) you could indulge yourself for more insight.

Thanks, @neelxie, for the explanation, it is more clear now 
And l think you are now good to go

**Review by jennizalwango — APPROVED** [review]

**Pull request merged**
