### PR TITLE
 #166187813 Setup Sass pre-processing for Project

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Set up Sass Pre-processing for project

#### Description of Task to be completed?

Install node-sass and sass-loader
Install css-loader and style-loader
Configure Sass in webpack.config file

#### How should this be manually tested?

* -	Git fetch this branch in the terminal with `git fetch origin ch-setup-sass-166187813
* -	Install application dependencies: `npm install`
* -	Run the application: `npm start`
* -       The app should show this:

Screenshot 2019-07-05 at 17 47 08

* -	You can go to the `app.scss` file and add in any css code and you will see it effected in the browser. The above image shows blue text because this is what the `app.scss` file contains.

Screenshot 2019-07-05 at 17 35 14

#### Any background context you want to provide?

This application did not have a sass pre-processors set up but I have set it up

#### What are the relevant pivotal tracker stories?

#[166187813](https://www.pivotaltracker.com/story/show/166187813)

### CODE REVIEW

**Review by jennizalwango — COMMENTED** [review]
Hey @neelxie, Good work on the work done, l have tested out the application and everything works fine as you said though if you could look into changing the description on your PR,
Screenshot 2019-07-05 at 9 07 52 PM
Especially this part we fetch the branch but not the repo, then you checkout to that branch
Then another thing l suggest you consider using scss variables instead of just the usual CSS.
Otherwise good work.

**Review by alexxsanya — COMMENTED** [review]
Screenshot 2019-07-06 at 15 17 31

@neelxie kindly edit that complaining import to the exact name of the file which is `App.scss` not `app.scss` and then we should be good to go.

**Comment by alexxsanya** [comment]
> Hey @neelxie, Good work on the work done, l have tested out the application and everything works fine as you said though if you could look into changing the description on your PR,
> Screenshot 2019-07-05 at 9 07 52 PM
> Especially this part we fetch the branch but not the repo, then you checkout to that branch
> Then another thing l suggest you consider using scss variables instead of just the usual CSS.
> Otherwise good work.


Screenshot 2019-07-06 at 15 29 44
@jennizalwango the above highlighted statement is actually confusing. the instructions clearly states fetching a branch not a repo. I guess you need to edit it to make meaning

**Comment by neelxie** [comment]
> Hey @neelxie, Good work on the work done, l have tested out the application and everything works fine as you said though if you could look into changing the description on your PR,
> Screenshot 2019-07-05 at 9 07 52 PM
> Especially this part we fetch the branch but not the repo, then you checkout to that branch
> Then another thing l suggest you consider using scss variables instead of just the usual CSS.
> Otherwise good work.

Thank you, @jennizalwango I have worked on your feedback.

**Comment by neelxie** [comment]
> Screenshot 2019-07-06 at 15 17 31
> 
> @neelxie kindly edit that complaining import to the exact name of the file which is `App.scss` not `app.scss` and then we should be good to go.

Thank you @alexxsanya I have worked on that feedback as shown below.

Screenshot 2019-07-08 at 09 48 00

**Comment by alexxsanya** [comment]
> > Screenshot 2019-07-06 at 15 17 31
> > @neelxie kindly edit that complaining import to the exact name of the file which is `App.scss` not `app.scss` and then we should be good to go.
> 
> Thank you @alexxsanya I have worked on that feedback as shown below.
> 
> Screenshot 2019-07-08 at 09 48 00

Awesome.

**Review by alexxsanya — DISMISSED** [review]
@neelxie kindly action on the comments by **hound** on your PR and we move forward.
Screenshot 2019-07-08 at 10 33 00

**Review by HabibSentongo — APPROVED** [review]
I see this runs well, I understand the review comments from **hound** app will be sorted when @jennizalwango 's PR gets merged with the right hound settings. So here we are good to go.

**Review by Emmanuelaaron — APPROVED** [review]
We are good to go.
Great job @neelxie

**Review by alexxsanya — APPROVED** [review]
@neelxie  nice work.

**Review by jennizalwango — APPROVED** [review]

**Pull request merged**
